Upload Images
RocketChat/RC4Conferences pull request #123
Opened 2023-03-09 17:22 UTC by imf-ali

This PR does:

- Able to add event header image
- Able to add event logo image
- Able to crop images

Fix #98

2023-03-09 17:25 UTC, imf-ali commented
Hey @Dnouv, please have a look at the PR.

2023-03-25 14:00 UTC, Dnouv requested changes

2023-03-30 07:00 UTC, imf-ali commented on app/package.json
> +    "@material-ui/core": "^4.12.4",
Fixed

2023-03-30 07:01 UTC, imf-ali commented
Hey @Dnouv, I have done the required changes. Please have a look.

2023-04-08 17:11 UTC, imf-ali commented
@Dnouv can you have a look at it?

2023-04-15 07:38 UTC, merged