[NEW] : backport improve navbar #73
RocketChat/RC4Conferences pull request #88
Opened 2023-01-18 12:47 UTC by Aashray446

### DEMO
![pr-3](https://user-images.githubusercontent.com/69245931/213174496-8be6081d-63e6-465f-b321-59a923901715.gif)

2023-01-20 11:03 UTC, Aashray446 commented
@Dnouv I saw that you have assigned the issue to me, I have raised a PR for that issue :sweat_smile:

2023-01-21 14:31 UTC, Dnouv requested changes

2023-01-21 14:31 UTC, Dnouv commented on app/components/menubar/newMenuBar.js
> +                              <div key={key} className={'p-2 fw-medium' + ` ${item.attributes.style === 'disable' ? styles.disabled : ''}`}>
Could we change the style for disabled and link items? 

![image](https://user-images.githubusercontent.com/61188295/213871132-cffcaacb-2056-40a7-aaf6-481f83663574.png)

In the above image, the `disabled` item (`GSoC 2022`), which serves as a heading for categories (`GSoC 2022 Demo Day`), is not easily distinguishable. 

Another note:

Please keep the Nav Links in the left corner:
![image](https://user-images.githubusercontent.com/61188295/213871450-3faad748-dd5e-4766-830d-7872f4af60c1.png)
 (Something like above)

2023-01-21 14:31 UTC, Dnouv commented on app/components/menubar/newMenuBar.js
> +                    className={`${styles.dropdown} d-flex flex-row justify-content-between align-items-center mt-3 `}
This Error occurs when opening the Nav items

![image](https://user-images.githubusercontent.com/61188295/213871346-a555c626-f81c-4f97-98c5-01ee6b459bcb.png)

2023-01-21 14:33 UTC, Dnouv commented
Thanks for the PR. Nice work @Aashray446 :)

I have left some comments, please take a look.

2023-01-21 15:01 UTC, Aashray446 commented
> Thanks for the PR. Nice work @Aashray446 :)
> 
> I have left some comments, please take a look.

Yeah Sure, I will fix those issues and will also suggest something for the disabled nav links asap.

2023-01-21 16:41 UTC, Aashray446 commented
@Dnouv 
![image](https://user-images.githubusercontent.com/69245931/213876253-25d0b7c0-016e-4e1c-8989-dd59de976612.png)
![image](https://user-images.githubusercontent.com/69245931/213877251-774bea04-6947-4cab-9e02-b96d90717fc0.png)

Any one of them is ok ? or should I experiment with color ?

2023-01-22 06:14 UTC, Dnouv commented
The second one looks good. Just a minor addition, add a hover effect whenever the user hovers over the links ("GSoC 2022 Demo Day"); it should turn to "Blue"/"Red" color to indicate they are links.

Thank you!

2023-01-22 08:19 UTC, Aashray446 commented
@Dnouv I have made the changes and solved the error, Here is the current working Screenshot.
I have rebased and then commit the changes, Should I make a new PR? 
![pr-5](https://user-images.githubusercontent.com/69245931/213906659-753e14f5-192a-4d58-b95a-d7308a1fdfda.gif)

2023-01-24 06:24 UTC, Dnouv commented
Thanks for the PR & Congrats 🎉 on your first PR. LGTM!

2023-01-24 06:25 UTC, merged